const CHARACTERS = {
    ALBEDO: 'Albedo',
    AMBER: 'Amber',
    BARBARA: 'Barbara',
    BEIDOU: 'Beidou',
    BENNETT: 'Bennett',
    CHONGYUN: 'Chongyun',
    DILUC: 'Diluc',
    DIONA: 'Diona',
    FISCHL: 'Fischl',
    JEAN: 'Jean',
    KAEYA: 'Kaeya',
    KEQING: 'Keqing',
    KLEE: 'Klee',
    LISA: 'Lisa',
    MONA: 'Mona',
    NINGGUANG: 'Ningguang',
    NOELLE: 'Noelle',
    QIQI: 'QIQI',
    RAZOR: 'Razor',
    SUCROSE: 'Sucrose',
    TARTAGLIA: 'Tartaglia',
    VENTI: 'Venti',
    XIANGLING: 'Xiangling',
    XINGQUI: 'Xingqui',
    XINGYAN: 'Xingyan',
    ZHONGLI: 'Zhongli'
};

export default CHARACTERS;